name: TimeZones
main: TimeZones\TimeZones
version: 1.1
api: 1.0.0
description: A commision plugin for time plugin.
#View more here: https://forums.pocketmine.net/threads/time-zones.7624/
author: HotFireyDeath

commands:
 tz:
  description: "Shows the current time"
  usage: "/time"
  permission: TimeZones.time

